### ISSUE TITLE
The code release time？

### ISSUE THREAD

**Issue by Hongbo123467** [ispc-lab/UMC#1]

**Comment by TianhangWang** [comment]
Thansks for your interests! We have relesed the codes for the early access and remaining contents will be added as soon as possible. Please give us more time to sort, thanks a lot.

**Comment by Hongbo123467** [comment]
Thanks for your enterprising work, and I noticed that you have added GNSS and IMU matrix for GRU hidden feature  which is not mentioned in your paper. So I am wondering how to get them from V2XSim dataset and their effects.Looking forward to hearing from you soon.

**Comment by TianhangWang** [comment]
Hi! Thanks for your great interests in our work! 

1. First, To better paper understanding, we have moved the detailed formulas of GRU process to the supplements. You can actually check it for more details. Here are some snaps, I hope it can be helpful for you. 
![image](https://github.com/ispc-lab/UMC/assets/42128414/707c78a5-d39d-464f-a350-6a1b9e8719d1)

2. As for the GNSS and IMU data, we requested Yiming for more detailed about GNSS and IMU in V2X-Sim 1.0 version, he sent us a copy of GNSS and IMU data. At now, these information has been added in V2X-Sim 2.0 version, which can be found in this [cite](https://pan.baidu.com/s/1oZ3AV17f3C-zd1lTooPLOQ?pwd=v2xs#list/path=%2FV2X-Sim%202.0). You can check it for more details. And our GNSS/IMU code scripts will be released soon. Notice that if you don't mind the unsorted scripts version, please kindly refer to this [cite](https://gist.github.com/TianhangWang/85fb5b930c179e481545dc214f407ebe).
