### ISSUE TITLE
OPV2V2V2XSIM

### ISSUE THREAD

**Issue by Hongbo123467** [ispc-lab/UMC#2]
我使用提供的api将OPV2V转为V2XSIM格式，但是在读取json文件时，会出现以下报错

![1695390822945](https://github.com/ispc-lab/UMC/assets/63486553/6141fcca-cd61-435b-9bc8-d8518430e618)

**Comment by TianhangWang** [comment]
您好，个人感觉可能是由于您的初始文件夹文件格式与我pipelinev3.py的不一致，后续我会将具体的文件排布格式以及对应生成的OPV2V的文件放到百度网盘上，请您一一对照一下。感谢您的提问！

**Comment by TianhangWang** [comment]
我刚才检查了一下百度网盘，如果您需要我处理好的OPV2V的数据的话，请您访问以下链接：[opv2v_train](https://pan.baidu.com/s/1cmZaXjaaB7durIhr2N880w)[提取码：dl3i]，[opv2v_test](https://pan.baidu.com/s/1worCYPXvhGjqfbF_na8teg)[提取码：hrr1]，[opv2v_test_culver](https://pan.baidu.com/s/18i3UYDOCV6ciafaa5xmIrA)[提取码：1zow]，请您及时查收。
同时，后续我们将更新全部代码的使用手册，请您理解！

**Comment by Hongbo123467** [comment]
很感谢您的解答，我想要将V2V4real转为V2Xsim的格式，但是遇到了上面的问题，好像是json文件在写入时的格式问题，导致在解析时end与字符串长度不匹配，期待您的更新

**Comment by TianhangWang** [comment]
感谢您的提醒，后续我们也会继续推进V2V4Real的转换工作，谢谢您将我们的api应用到更为广泛的数据集上并提供反馈！
