### ISSUE TITLE
train_codet_MRSR.py报错

### ISSUE THREAD

**Issue by Wesley-wsj** [ispc-lab/UMC#3]
我在使用您在上个issue中提供的opv2v数据集时，出现了如下报错，劳烦您解答一下，感谢！
![image](https://github.com/ispc-lab/UMC/assets/152406043/9b0802a5-87e9-4b3a-ad1c-77545b07314b)

**Comment by TianhangWang** [comment]
实在不好意思，是这样的，当初在V2X-SIM的数据集上探究了添加ROI监督的方法，但发现效果不佳；所以后续我们在OPV2V数据集上就没有再另外添加ROI监督的标签了，所以OPV2V和V2XSIM的训练代码有一些小小的不同；为了方便您更快的使用起来，我简单把需要改的地方截屏了，您试一下，是不是不会报错了：

- For train_codet_MRAR.py 

1. V2X-SIM version:

![image](https://github.com/ispc-lab/UMC/assets/42128414/890f43cf-2109-419b-8f5c-fcbffa7b753f)

![image](https://github.com/ispc-lab/UMC/assets/42128414/97074389-e13c-48b6-b35f-1376dbe020c0)

2. OPV2V version:

![image](https://github.com/ispc-lab/UMC/assets/42128414/8c4523b1-70ea-4050-8ccb-6cbef22cdb43)

![image](https://github.com/ispc-lab/UMC/assets/42128414/a03d4032-f10c-486b-89fd-d374b1b9ec0f)

- For Dataset.py

OPV2V 额外需要注释掉这些带ROI的地方：

![image](https://github.com/ispc-lab/UMC/assets/42128414/7ce0b9a2-48df-45ac-9f1d-87904a5f86d4)

![image](https://github.com/ispc-lab/UMC/assets/42128414/70af7962-920d-486e-83ad-5d1ef830d5a1)

![image](https://github.com/ispc-lab/UMC/assets/42128414/7a0337cf-defa-424a-81c9-ecdcb42a8a32)

![image](https://github.com/ispc-lab/UMC/assets/42128414/ccecdeea-1f64-49e3-8307-0bb77841534a)

个人发现的地方就是这些，如果还有没找到的报错，您直接注释掉就可以了；最后，我们对BUGs对您带来的困扰表示道歉，再次感谢您使用我们的代码！

**Comment by Wesley-wsj** [comment]
作者你好，根据您的修改方法代码已经正常运行，感谢您的及时回复！

**Comment by TianhangWang** [comment]
收到，没问题就OK，那我先把issus关了，您有问题再开过。愿您科研顺利！
